### ISSUE TITLE
Weather System

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#160]
The original server has some kind of a "Weather System". If you played the game, then you probably noticed that it rains sometimes in Lorencia (but not with this Server yet) ;-)

## Logic
The Server changes the weather of all hosted maps in a random interval of 10000 to 20000 ms which is checked every 1000 ms.

I suggest to implement it somewhere outside the GameMap class, as it's not a required core logic, but more likely an AddOn. We could introduce some kind of a "IPeriodicTaskPlugIn" interface which are initialized when the game is initialized, e.g. after the game maps are created. The weather logic could implement such a plugin interface. The interface could include a property for the Interval and an Execute method. This could be helpful in other similar periodic tasks, e.g. game events.

## Tasks:
* [x] Add packet definition for the weather message (0x0F)
  * [ ] Find out how the different random values affects the weather in the game client. Add meaningful enumerations, if it makes sense. See description below.
* [x] Add a view plugin interface to notify about weather updates
* [x] Add IPeriodicTaskPlugIn interface.
* [x] Implement initialization/execution of all available IPeriodicTaskPlugIns
* [x] Implement IPeriodicTaskPlugIn for the Weather logic. It randomly generates a new weather every 10-20 seconds for each map and invokes the view plugin for each player on the map.
* [x] Implementation of the view plugin interface, which sends the defined weather message to the game client

## Message structure
It starts C1 04 0F and is followed a byte which contains the information about the weather.
This byte consists of two parts of each 4 bit:
* The higher nibble (left shifted by 4) is a random number between 0 and 2 (inclusive). It's called "Weather" and is probably a value for "sunny", "rainy", etc. I'm not sure if it means the same for every possible map.
* The lower nibble is a random number between 0 and 9 (inclusive). It's called "Variation" and is probably some kind of an intensity.

**Comment by SmileYzn** [comment]
This is true in webzen server:

`			case 1000 :

				{
				for( int n=0; n<g_TerrainManager.Size(); n++)
				{
					MapC[n].WeatherVariationProcess();
				}`

:P

**Comment by sven-n** [comment]
yes, and I described what happens there in my first post ;)

> The Server changes the weather of all hosted maps in a random interval of 10000 to 20000 ms which is checked every 1000 ms.

**Comment by sven-n** [comment]
> Find out how the different random values affects the weather in the game client. Add meaningful enumerations, if it makes sense. See description below.

I couldn't really find out which effects these values have. I saw no differences in weather effects in the game client :-/

**Comment by SmileYzn** [comment]
Check crywolf, has weather o/

**Comment by sven-n** [comment]
thanks for the hint, I’ll :)
