### ISSUE TITLE
Implement a Quest System

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#51]
## Current state
MU Online itself has two different quest systems (Class Changes etc. and Elf Soldier quests). It would be great if we could implement them in a generalized way. Only the view should decide which data packets are sent to the client.

### Documentation
I documented the messages for the older quest system (C1A0 to C1A4) already. It's used for the character class evolution and the combo skill.

The elf soldier provides another quest system. It uses different messages (C1F6) and usual quests are built to kill x monsters to get experience or items as reward. I documented these messages as well.

## Quest state as attribute value
Some skills require that certain quests have been completed, e.g. Crystal of Destruction requires that the "Marlon Quest" is done. Usually the client checks these quest states itself. To prevent cheating, the server has to do this, as well.

Idea:
  * Quest state as Attribute Value of a Character
  * Quest state as Attribute Requirement (Skill.Requirements)

A quest definition could define if the completed quest should add an attribute value to the character.
These attribute values could also be used further, for example as requirement for maps or to wear items.

## Client interaction

The player view has to be extended to be able to send the quest state(s). As I wrote above, there should be a generalized view interface for quests.
The view implementation can then decide which messages (depending on the quest system) should be sent to the client. Ideally, the game logic should make no difference about the different quest systems.

## Tasks
* [x] Old Quest System (Level 150, 220, ...)
* [x] New Quest System
  * [x] Message structs, plugins
  * [x] Logic
  * [x] Initialization data
  * [x] Testing
* [x] Quest completion states as attribute requirements for some skills

**Comment by sven-n** [comment]
> To get some game features done, I started to begin implementing the quest system. It’s currently still incomplete. The first thing which was done is defining all the required network message structures and implementing the corresponding View- and PacketHandler-Plugins. Then I went further and tried to make some sense out of packets I captured a decade ago on the original Global MU Online server and implemented some of the game logic.
Now, what’s missing is the initialization data for all the available quests and a lot of testing ;)

The current state is at the [quest branch](https://github.com/MUnique/OpenMU/tree/quest).

**Comment by sven-n** [comment]
I‘m close of finishing the first of the two quest systems (level 150, 220, 380, 400 quests). As soon as I have that, I‘ll merge the branch into master. It‘ll contain some changes which are required to fix #150 :)

**Comment by sven-n** [comment]
I'm closing this now as the quest system is implemented. If there are any remaining problems, please open a new issue.
